### ISSUE TITLE
NORTH-app only shows progress bar

### ISSUE THREAD

**Issue by mictadlo** [nibtehaz/NORTH-app#1]
Hi,
I tried NORTH-app and I only got a description of NORTH and a progress bar. NORTH-app is running for a 1h and the progress bar did not disappear on my Debian (testing) environment. 

Is it possible that I miss anything?

Thank you in advance,

Michal
![Screen Shot 2019-04-03 at 7 06 41 PM](https://user-images.githubusercontent.com/588297/55918974-8ffa1a00-5c37-11e9-9016-8dee6802cd18.png)

**Comment by nibtehaz** [comment]
Hello, sorry to hear that, I thought our email conversations fixed the issue.

First of all I'd request you to download/clone the latest version of the code, since I made some changes.

As I'd said earlier since the progress bar is being showed, the nodeJs part is working fine. So most likely the python part is causing the troubles.

Therefore, I would request you to run the following command

`python3 app.py`

After running this command, a flask server will be served from [localhost:5000](localhost:5000). Two things may happen
1) The server wouldn't start
2) The server would start, but if you go to localhost:5000 or 127.0.0.1:5000 it will show a 404 or 500 error.

Whether the case, the terminal would display some errors. Please, kindly show me the errors and I'll try to fix the issues.

I am very sorry for all the inconveniences. At present, I can't understand what's causing these issues since the app worked fine in my development pc and another independent testing pc. I would really appreciate if you send me the errors, thanks in advance.

**Comment by mictadlo** [comment]
Hi,
Thank you for your massage, I am sorry I must have overlooked your email. I ran `python3 app.py` and it turned out I had the following packages missing:
```
pip3 install tqdm
pip3 install pandas
pip3 install matplotlib
pip3 install seaborn
apt-get install python3-tk
```
After installing the above package NORTH worked.

Michal

**Comment by nibtehaz** [comment]
Hi,
Thanks a lot, Michal, I'm glad that the app is working correctly now.

However, my bad. To run the gui app you wouldn't need tqdm, matplotlib, seaborn. They were actually required for generating the experimental results used in the paper. I did try to remove these from the codes of the app, perhaps, some portion of them still remained. I'll try to filter them out and remove them to resolve the same issues arising later (or I could have just added them to the requirements but that would be redundant).

I would like to apologize for the problems you faced and thank you for pointing out these issues to me.

Have a great day, thanks for your interest in our NORTH project :)
